"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
format = """
$directory$git_branch$git_status$cmd_duration
$character"""
right_format = """$package$nodejs$python$rust$golang$docker_context"""
command_timeout = 10000

[character]
success_symbol = '[❯](bold #A3BE8C)'
error_symbol = '[❯](bold #BF616A)'
vimcmd_symbol = '[❮](bold #B48EAD)'

[cmd_duration]
min_time = 2_000
format = '[ $duration]($style) '
style = 'bold #D8DEE9'

[directory]
style = 'bold #88C0D0'
format = '[ $path ]($style)[$read_only]($read_only_style)'
read_only_style = 'bold #BF616A'
read_only = ' '

[git_branch]
format = '[$symbol$branch(:$remote_branch) ]($style)'
style = 'bold #88C0D0'
symbol = " "

[git_status]
format = '[$all_status$ahead_behind]($style) '
style = 'bold #88C0D0'
conflicted = ' '
ahead = '⇡${count} '
behind = '⇣${count} '
diverged = '⇕⇡${ahead_count}⇣${behind_count} '
untracked = ' '
stashed = ' '
modified = ' '
staged = ' '
renamed = '󰑕 '
deleted = ' '

[gcloud]
disabled = true

[nodejs]
format = '[$symbol($version)]($style) '
symbol = ' '
style = '#A3BE8C'

[python]
format = '[$symbol$version]($style) '
symbol = ' '
style = '#B48EAD'

[rust]
format = '[$symbol($version)]($style) '
symbol = ' '
style = '#BF616A'

[golang]
format = '[$symbol($version)]($style) '
symbol = ' '
style = '#88C0D0'

[docker_context]
format = '[$symbol$context]($style) '
symbol = ' '
style = '#88C0D0'

[package]
format = '[$symbol$version]($style) '
symbol = '󰏗 '
style = '#D8DEE9'
