"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
format = """$directory$fill$git_branch$git_status$cmd_duration$package$nodejs$python$docker_context
$character"""
command_timeout = 10000

[fill]
symbol = ' '

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'
vimcmd_symbol = '[❮](bold purple)'

[cmd_duration]
min_time = 2_000
format = "[\uf252 $duration]($style)"
style = 'bold purple'

[directory]
style = 'bold blue'
format = "[\uf115 $path]($style)[$read_only]($read_only_style)"
read_only_style = 'bold red'
read_only = "\uf023 "

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
style = 'bold cyan'
symbol = "\ue0a0 "

[git_status]
format = '[$all_status$ahead_behind]($style)'
style = 'bold cyan'
conflicted = "\uf0e7 "
ahead = '↑${count} '
behind = '↓${count} '
diverged = '↕↑${ahead_count}↓${behind_count} '
untracked = "\uf128 "
stashed = "\uf01c "
modified = "\uf044 "
staged = "\uf067 "
renamed = '󰑕 '
deleted = "\uf014 "

[gcloud]
disabled = true

[nodejs]
format = '[ $symbol($version)]($style)'
symbol = "\ue718 "
style = 'green'

[python]
format = '[ $symbol$version]($style)'
symbol = "\ue73c "
style = 'purple'

[rust]
disabled = true

[golang]
disabled = true

[docker_context]
format = '[ $symbol$context]($style)'
symbol = "\uf308 "
style = 'blue'

[package]
format = '[ $symbol$version]($style)'
symbol = '󰏗 '
style = 'blue'
