# vim: ft=tmux
# ~/.dotfiles/.config/tmux/statusline.conf

set -g status on
set -g status-interval 5
set -g status-justify left
set -g status-left-length 100
set -g status-right-length 100
set -g status-left-style NONE
set -g status-right-style NONE

set -g status-style "fg=#586e74,bg=#002d38"
set -g mode-style "fg=#ede7d4,bg=#073541"
set -g message-style "fg=#ede7d4,bg=#073541"
set -g message-command-style "fg=#ede7d4,bg=#073541"

set -g status-left "#[fg=#002d38,bg=#ede7d4,bold] #S:#I.#P #[fg=#ede7d4,bg=#adb8b8]#[fg=#00141a,bg=#adb8b8,bold] #(whoami) #[fg=#adb8b8,bg=#002d38]"
set -g status-right "#[fg=#647a82,bg=#002d38]#[fg=#adb8b8,bg=#647a82]#[fg=#00141a,bg=#adb8b8,bold] #h "

setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#9fabad,bg=#002d38"
setw -g window-status-format " #I  #{b:pane_current_path} "
setw -g window-status-current-format "#[fg=#002d38,bg=#ede7d4]#[fg=#b28600,bg=#ede7d4,bold] #I #[fg=#ede7d4,bg=#b28600]#[fg=#002d38,bg=#b28600,bold] #{b:pane_current_path} #[fg=#b28600,bg=#002d38]"
