# vim: ft=tmux
# ~/.dotfiles/.config/tmux/statusline.conf

set -g status on
set -g status-interval 5
set -g status-justify left
set -g status-left-length 100
set -g status-right-length 100
set -g status-left-style NONE
set -g status-right-style NONE

set -g status-style "fg=#9eabac,bg=#002c38"
set -g mode-style "fg=#ede7d3,bg=#063540"
set -g message-style "fg=#ede7d3,bg=#063540"
set -g message-command-style "fg=#ede7d3,bg=#063540"

set -g status-left "#[fg=#ede7d3]#[fg=#001419,bg=#ede7d3,bold]#S#[fg=#ede7d3,bg=#002c38] #[fg=#063540]#[fg=#9eabac,bg=#063540]#(whoami)#[fg=#063540,bg=#002c38] "

setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#637981,bg=#002c38"
setw -g window-status-format " #I  #{b:pane_current_path} "
setw -g window-status-current-format "#[fg=#b28500]#[fg=#001419,bg=#b28500,bold] #I #{b:pane_current_path} #[fg=#b28500,bg=#002c38]"

set -g status-right "#[fg=#063540]#[fg=#29a298,bg=#063540]#(git -C '#{pane_current_path}' branch --show-current 2>/dev/null)#[fg=#063540,bg=#002c38] #[fg=#063540]#[fg=#b28500,bg=#063540]#(pmset -g batt | grep -q 'AC Power' && printf '' || printf '') #(pmset -g batt | awk 'NR==2{print $3+0}')%%#[fg=#063540,bg=#002c38] #[fg=#063540]#[fg=#9eabac,bg=#063540]%H:%M#[fg=#063540,bg=#002c38] "
