# vim: ft=tmux
# ~/.dotfiles/.config/tmux/statusline.conf

set -g status on
set -g status-interval 5
set -g status-justify left
set -g status-left-length 100
set -g status-right-length 100
set -g status-left-style NONE
set -g status-right-style NONE

set -g status-style "fg=#9fabad,bg=#002d38"
set -g mode-style "fg=#ede7d4,bg=#073541"
set -g message-style "fg=#ede7d4,bg=#073541"
set -g message-command-style "fg=#ede7d4,bg=#073541"

set -g status-left "#[fg=#ede7d4]#[fg=#00141a,bg=#ede7d4,bold]#S#[fg=#ede7d4,bg=#002d38] #[fg=#073541]#[fg=#9fabad,bg=#073541]#(whoami)#[fg=#073541,bg=#002d38] "

setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#647a82,bg=#002d38"
setw -g window-status-format " #I  #{b:pane_current_path} "
setw -g window-status-current-format "#[fg=#b28600]#[fg=#00141a,bg=#b28600,bold] #I #{b:pane_current_path} #[fg=#b28600,bg=#002d38]"

set -g status-right "#[fg=#073541]#[fg=#2aa298,bg=#073541]#(git -C '#{pane_current_path}' branch --show-current 2>/dev/null)#[fg=#073541,bg=#002d38] #[fg=#073541]#[fg=#b28600,bg=#073541]#(pmset -g batt | grep -q 'AC Power' && printf '' || printf '') #(pmset -g batt | awk 'NR==2{print $3+0}')%%#[fg=#073541,bg=#002d38] #[fg=#073541]#[fg=#9fabad,bg=#073541]%H:%M#[fg=#073541,bg=#002d38] "
