# ~/.dotfiles/.config/tmux/theme.conf
# solarized-osaka, the same palette Neovim loads.

set -g status-style "bg=#002d38,fg=#9fabad"

setw -g window-status-style "fg=#647a82,bg=#002d38"
setw -g window-status-current-style "fg=#b28600,bg=#073541,bright"

set -g pane-border-style "fg=#073541"
set -g pane-active-border-style "fg=#2aa298"

set -g message-style "bg=#073541,fg=#ffbf00"

set -g display-panes-active-colour "#278bd3"
set -g display-panes-colour "#b28600"
setw -g clock-mode-colour "#859900"
